### PR TITLE
Experiment copyleft exception (closes #15)

### LINKED ISSUE #15: Consider a grace period for private development
Should the license build in a grace period for development of code covered by copyleft, so that developers can work in private leading up to contribution?

Note that the general automatic-cure terms of Excuse don't cover knowing violation of the rules.

Thanks to @jberkus for this one!

### PR DESCRIPTION
**Pull request by kemitchell**
This pull request:

1. Adds a general deadline of thirty calendar days to contribute software when required.

2. Adds an exception to copyleft for experimental code.

### CODE REVIEW

**Comment by bhilburn** [comment]
I think this is moving in the right direction! A couple of points of feedback:

[Minor note: `other than software that simply invoke this software through the interfaces it exposes.` in top change should be `invokes` - my copy, below, reflects that typo fix.]

1. I think there is a bit of bouncing back and forth with phrasing that is confusing.

At the top, we have:
```
...requires you to contribute source code ... other than software that simply invokes this software through the interfaces it exposes.
```

Then:
```
With two exceptions, you must contribute other software that invokes this software's functionality...
```

Then:
```
You need not contribute other software that only invokes this software's functionality through the interfaces this software exposes
```

As a reader, understanding what the license is saying with regard to contributing source for "software that invokes this software's functionality" can be somewhat difficult to follow, I think. The flow is "you must contribute" --> "other than..." --> "with exceptions" --> "you must contribute" --> "you need not contribute".

I don't think there are any logical errors with this - it's simply a readability suggestion.

2. I think the two different timeframes actually overlap each other, thus giving conflicting instructions? Under "Exceptions", it says if it's experimental and you don't use it for more than 14 days, you don't have to Contribute. Under "Contribution", it says if you must contribute, it must be done within 30 days.

So, if I write experimental software and use it for 15 days, I'm in violation of the 14-day experimental window, but actually still comply with the license (?) because I actually have 30 days to contribute.

**Comment by kemitchell** [comment]
@bhilburn, thanks so much for great feedback! I've pushed a few commits trying to address your points. I've also created a pull request to this branch, #23, with a potential readability improvement.

**Comment by kemitchell** [comment]
@bhilburn I've just fast-forwarded master to a branch with an experimental software exception, now called "Prototypes".

**Comment by bhilburn** [comment]
@kemitchell - I really like the approach you took of hyperlinking the keywords to their definitions within the license 👍

**Pull request closed without merging**
