### PR TITLE
Break up mega-sentence in "copyleft"

### PR DESCRIPTION
**Pull request by tieguy**

### CODE REVIEW

**Comment by kemitchell** [comment]
You're right. It's a mega-sentence.

I'd prefer to fix it without a lawyer-style definition. How about this?:

> You need not contribute applications that only invoke this software's functionality through the interfaces this software exposes, without exposing this software's interfaces and functionality to other applications. However, you must contribute other software that invokes this software's functionality, as well as any changed or extended versions of this software.

**Comment by kemitchell** [comment]
96f763a0abf5762341c565e96a1b803a16a0f78f

**Comment by tieguy** [comment]
Take your point on definitions (submitted it only reluctantly, time is tight right now).

Not a fan of reversing the order - exception before rule? Will continue to ponder how that might be done better.

**Comment by kemitchell** [comment]
@tieguy Welcome further thoughts! I was eager to merge something to `master` here, as new eyeballs are coming in.

**Pull request closed without merging**
