### PR TITLE
Contribution: Explicitly prevent relicensing

### PR DESCRIPTION
**Pull request by kemitchell**
In response to https://twitter.com/HerraBRE/status/1088238705050038275

I'm not sure this is necessary, but it may be helpful.

### CODE REVIEW

**Comment by bhilburn** [comment]
So, I don't think it's necessary, as it has no legal effect on the license, and while it might be somewhat helpful, I don't think it actually directly addresses the cause of confusion. I'll elaborate:

I actually got tripped up on a related point the first time I read through the license. Specifically, on the language:

```
license parts of that software that haven't already been contributed
```

In order to properly parse that clause, the reader must understand that the mainline distribution of the software, as published under this license, has already been `contributed`. I think this is counter-intuitive to the way most developers would read this, myself included. Yes, the upstream includes `contributions`, but thinking of the entire distribution as having been `contributed` only makes sense within the definition of `Contributing` as this license describes it.

I recognize that some of the difficulty, here, is that you have to somehow wrap up not only extensions to the original software, for example, but entirely different projects that are acting as 'service-wrappers'.

Here's my off-the-cuff suggestion that is almost definitely wrong but hopefully communicates the idea:

```
Second, ensure that all parts of the software have been licensed in one of the following ways:
```

**Comment by bhilburn** [comment]
Just realized the issue with my suggestion at the end of my last comment, which that it kind of sounds like it actually allows relicensing, hah.

Attempt two:
```
Second, ensure that all other parts of the software, other than this software, have been 
licensed in one of the following ways:
```

Obviously that's clunky and prone to error with the different meanings of `software`, but hopefully it's illustrative of the goal :)

**Comment by kemitchell** [comment]
@bhilburn, excellent feedback and suggestions! Let me try my hand at a clarification...

**Comment by kemitchell** [comment]
> In order to properly parse that clause, the reader must understand that the mainline distribution of the software, as published under this license, has already been contributed. I think this is counter-intuitive to the way most developers would read this, myself included.

You're right.

This was an artifact of my work on Parity, which intentionally emphasizes that the licensor and downstream users subject to copyleft "contribute" likewise. This license isn't making the same equivalence, rhetorically, so that approach to license-what-how didn't make sense.

**Comment by kemitchell** [comment]
@bhilburn, does 5694783ffeca622fa6dfaf4f67aa24ab8c4cb52c read better?

**Comment by bhilburn** [comment]
@kemitchell - Yes, very much so. The consistent use of `that software` and `that source code`, I think, goes a long way to making the clear distinction about what is being licensed. I consider this to be a resolution to my issues, as described above.

**Comment by kemitchell** [comment]
@bhilburn, awesome! Thanks so much!

**Pull request merged**
